# demo source: https://fastapi.tiangolo.com/
# https://fastapi.tiangolo.com/tutorial/path-params/
# localhost:8000/docs or /redocs for swagger api docs or redoc api docs; autogenerated
# python3.10 -m uvicorn fastapi_demo:app --reload --port 3000
from typing import Union
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()


# JSON model
class Item(BaseModel):
    name: str
    price: float
    is_offer: Union[bool, None] = None


@app.get("/")
def read_root():
    return {"Hello": "World"}


@app.get("/items/{item_id}")
def read_item(item_id: int, q: Union[str, None] = None):
    return {"item_id": item_id, "q": q}


@app.put("/items/{item_id}")
def update_item(item_id: int, item: Item):
    return {"item_name": item.name, "item_price": item.price, "item_id": item_id}
